### ISSUE TITLE
Document how to run a testnet node

### ISSUE THREAD

**Issue by leto** [MyHush/hush#10]
### Describe the issue

We need docs on how to run a testnet node, or else nobody will know how.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. No
2. Docs
3. TO RTFM

### Expected behaviour

To be able to RTFM

### Actual behaviour + errors

No RTFMing possible

### The version of Hush you were using:
ALL

**Comment by madbuda** [comment]
- [ ] Create TESTNET.md
- [ ] Update README.md with link to TESTNET.md

**Comment by leto** [comment]
This is nicely documented in https://github.com/MyHush/hush/blob/dev/Testnet.md now, I think we just need to add a link to it from README.md

**Comment by dawqfoundation** [comment]
not safe for newbies
