### ISSUE TITLE
Mine a regtest Genesis Block for testing

### ISSUE THREAD

**Issue by leto** [MyHush/hush#100]
### Describe the issue
No regtest genblock

#### If so, please list the steps to reproduce below:
1. No 
2. Regtest
3. GenBlock

### Bounty

100 Hush

### Expected behaviour
Devs should be able to run RPC tests/other in regtest mode.

### Actual behaviour + errors
Doesn't exist, can't run the tests

### The version of Hush you were using:
All

**Comment by FireMartZ** [comment]
I'll have a look at this.

**Comment by leto** [comment]
Merged https://github.com/MyHush/hush/pull/106, keeping this open until @FireMartZ gets paid his bounty. Awesome work!!!

**Comment by leto** [comment]
https://explorer.myhush.org/tx/de850091c420dd815a32fb358c0c330ba743e0d4b1411339bf9f816e1b50edca
