### ISSUE TITLE
RPC problem

### ISSUE THREAD

**Issue by oneevil** [MyHush/hush#116]
Hush node 1.0.13
While the block is submitted to rpc node stops to respond to any other commands. How is it possible to solve this issue?
BLOCK SUBMIT ERROR: <nil> Post http://127.0.0.1:8822: net/http: timeout awaiting response headers
We don't have this problem on Zcash.
node never responds once a hour + - a few minutes

**Comment by leto** [comment]
@oneevil can you tell us more details, like which commands you tried? Also, which OS does this happen? Thanks

**Comment by oneevil** [comment]
Fixed. 
Start node --disablewallet=1
