### ISSUE TITLE
Private vs Anonymous on myhush.org

### ISSUE THREAD

**Issue by leto** [MyHush/hush#12]
### Describe the issue

We need to very clearly explain privacy and anonymity on our homepage and how they relate to Hush.

#### If so, please list the steps to reproduce below:
1. Privacy
2. Does Not Equal
3. Anonymity

But our homepage confuses them.

### Expected behaviour

Privacy is not the same as anonymity, and we need to explain that to our potential users.

### Actual behaviour + errors

Teach people good stuff instead of spreading FUD

**Comment by leto** [comment]
![my hush 2017-08-08 09-18-48](https://user-images.githubusercontent.com/30298/29083177-a4fd01f8-7c1c-11e7-8b83-679a38ce7c7e.png)

This image is wrong wrong wrong, it confuses privacy and anonymity.

**Comment by leto** [comment]
I also don't like that it is a creepy dude in a trenchcoat. Normal average good people need privacy and anonymity too

**Comment by aayanl** [comment]
in some countries like China, the word `anonymous` carries a negative connotation due to censorship and `private` is preferred

**Comment by leto** [comment]
@aayanl that is a good point that we will take into account. thanks!

**Comment by matthewjamesr** [comment]
I am going to close this issue as it is more marketing related and can be discussed internal to the team on Slack.
