### ISSUE TITLE
reverse a payment sent to No Outputs after mined blocks

### ISSUE THREAD

**Issue by EvilRedHorse** [MyHush/hush#126]
When I say wallet I am talking hushd

### Describe the issue
I mined two blocks (a z-nomp based pool): Block# 305226 & 305446
they were gone a day later, sent to No Outputs on transaction#  e8436cf63cbb6a1805456d692cd122ec245db86ccb2ae70f447bd5731d7f2137
I am trying to get the blocks back in the wallet and cannot find documentation.

### steps
mine block to t-address
keep wallet synced

### Expected behaviour
money was to stay in wallet

### Actual behaviour + errors
Crashed hours after 2 mined blocks which were over 100 confirmations. 
After hushd was synced money was there.
Later it had been sent to No Outputs

### The version of Hush you were using:
Hush Daemon version v1.0.13-e44f3022

### Machine specs:
- OS name + version: FEDORA 27
- CPU: XEON 2011-3
- RAM: 8GB
- Disk size: 160GB
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a): Linux localhost.localdomain 4.15.10-300.fc27.x86_64 #1 SMP Thu Mar 15 17:13:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

### Any extra information that might be useful in the debugging process.
the wallet.dat and blockchain info are stored on a RAID5 BTRFS Array.

### Do you have a back up of `~/.hush` directory and/or take a VM snapshot?
'~/.hush' only contains my hush.conf file

**Comment by leto** [comment]
@EvilRedHorse "No Outputs" should really say "No public outputs" at

https://explorer.myhush.org/tx/e8436cf63cbb6a1805456d692cd122ec245db86ccb2ae70f447bd5731d7f2137

That means your funds were send to a zaddr.

Can you show us a screenshot of your transaction history? Are you using the SWING wallet? Please include version numbers, if so.

**Comment by EvilRedHorse** [comment]
Yes, I did eventually see the blocks received but that was after 24h with hushd synced. I am not using a swing wallet, I prefer hush-cli which I can wrap a simple GUI around, this problem could be moved to Z-NOMP git since the hush-coin-mining-payout was a shielded transaction by default causing a synced wallet to have a zero balance for 24h+ until the transaction completed. Thank you very much for your help.
