### ISSUE TITLE
Linux wallet encryption problem

### ISSUE THREAD

**Issue by leto** [MyHush/hush#13]
### Describe the issue
Wallet encryption on Linux is not working
```
error code: -16
error message:
Error: wallet encryption is disabled.
```

#### If so, please list the steps to reproduce below:
1.  Cannot
2. Use an encrypted Wallet
3. On Linux

### Expected behaviour

Wallets should be able to be encrypted.

### Actual behaviour + errors
Error above.

### The version of Hush you were using:

`“version”: 1000950,`

### Machine specs:
- OS name + version: Ubuntu 16.04

**Comment by leto** [comment]
This is related to and blocked on https://github.com/zcash/zcash/pull/1983

**Comment by madbuda** [comment]
@leto can we close this since it is tracked upstream?

**Comment by leto** [comment]
@madbuda :+1:
