### ISSUE TITLE
Large Hush transactions fail

### ISSUE THREAD

**Issue by leto** [MyHush/hush#14]
### Description

Getting an error when trying to send HUSH from my wallet to another address

`Error 16: bad-txns-oversize`

#### If so, please list the steps to reproduce below:
1. Send 300 Hush
2. In One
3. Transaction

### Expected behaviour
Should send 300 Hush.

### Actual behaviour + errors

Fails to send 300, gives error.

### The version of Hush you were using:
All

### Machine specs:
All

**Comment by leto** [comment]
This is a bug in our upstream zcash: https://github.com/zcash/zcash/issues/1961

**Comment by leto** [comment]
Workaround from the command line: `hush-cli $TADDR "[{\"address\": \"$FRIEND_TADDR\", \"amount\": 4.0}]" `

**Comment by leto** [comment]
Evidently 100Hush will trigger this, but 50 Hush works.

**Comment by radix42** [comment]
No, its not that zcash bug, that is about private transactions between zaddresses.....anytime  you see "JoinSplit" a zaddr is involved on one or both ends of things.

It is likely that there are too many utxo inputs, not the amount of HUSH sent.

**Comment by aayanl** [comment]
This is also a consensus level change and really really shouldn't be touched. Allowing really really large transactions acts as a DoS and fills up blocks fast

**Comment by leto** [comment]
@radix42 can we agree that a more user-friendly error here would be worthwhile?

**Comment by madbuda** [comment]
`Error 16: bad-txns-oversize
`
Seems legit, maybe a wiki entry or something giving some details when someone googles `hush Error 16: bad-txns-oversize`

**Comment by leto** [comment]
Meh, now this Github issue is searchable+findable and explain the core problem, I am calling this good
