### ISSUE TITLE
Create Hush 2.0.0 release

### ISSUE THREAD

**Issue by leto** [MyHush/hush#144]
This will track all the things needed to make our Hush 2.0.0 release, which is happening in the `release` branch. This is evolving and more stuff may be added

* [x] Change configure version to 2.0.0
* [x] Change version number in docs to 2.0.0
* [x] Update man pages via contrib/devtools/gen-manpages.sh, after changing configure version, make sure they say 2.0.0
* [x] Test latest code thoroughly, with txindex=0 and txindex=1
* [x] Create git tag
* [x] Add changelog notes to Github tag 
* [x] Make sure docs are updated to include new CLI options addressindex + friends
* [x] Once tag is created, merge dev to master

Optional/later:
* [ ] Update Gitian build stuff

**Comment by leto** [comment]
@radix42 if you are able to test the latest dev branch on any of your servers and/or OS's, that would be much appreciated!!! You can join the notary nodes in being some of the first nodes with DPoW-enabled Hush full nodes 😺

**Comment by leto** [comment]
Make this PR, I think it's pretty damn close to what 2.0.0 will be: https://github.com/MyHush/hush/pull/145

There could be some weird changes to files that are related to making binaries, but I am mostly worrying about creating a 2.0.0 tarball source code release.

**Comment by Scottrock** [comment]
Running latest dev branch, syncing chain from scratch.
hushd is writing MB to the debug.log
Daemon crashes regularly - I expect on log oversize

**Comment by leto** [comment]
@Scottrock sounds like you may have had a version of `dev` branch that had a coredump, latest dev and v2.0.0-rc branch have it fixed. It's normal to write lots to debug.log when syncing for the first time. Please let me know if you can still reproduce. I have been testing on multiple nodes with txindex=0 and txindex=1

**Comment by Scottrock** [comment]
Last dev branch I built synced fine - but I am one commit behind.
I should have time to build and start a new chain sync before leaving for work.

**Comment by leto** [comment]
donezo
