### ISSUE TITLE
EXCEPTION: St13runtime_error

### ISSUE THREAD

**Issue by egyptianbman** [MyHush/hush#161]
### Describe the issue

Random exception

#### If so, please list the steps to reproduce below:
1. Compile latest code on Linux
2. Run node
3. Logs report exception

### Expected behaviour
No exceptions

### Actual behaviour + errors
I occasionally see the following:
```
************************
EXCEPTION: St13runtime_error       
tinyformat: Too many conversion specifiers in format string       
Hush in ProcessMessages()       

ProcessMessages(headers, 120529 bytes) FAILED peer=47

************************
EXCEPTION: St13runtime_error       
tinyformat: Too many conversion specifiers in format string       
Hush in ProcessMessages()       
```

### The version of Hush you were using:
Run `hushd --version` to find out

### Machine specs:
- OS name + version: Ubuntu 18
- CPU: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
- RAM: MemTotal: 131701592 kB
- Disk size: 6TB
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): Linux d38072a29a43 4.16.12-200.fc27.x86_64 #1 SMP Fri May 25 21:10:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

**Comment by leto** [comment]
GIN recently enabled dpow and is seeing the same issues.

`Seems to be triggered when invalid blocks are received from outdated peers`

**Comment by egyptianbman** [comment]
Ah, in that case it's more of a warning than an error/exception.

**Comment by leto** [comment]
This warning happened when old non-updated Hush nodes try to talk to new dpow-enabled Hush nodes, and there was a printf() with an extra %d when logging this fact. It was not security-critical, but good to fix
