### ISSUE TITLE
Can't build on Manjaro/Arch

### ISSUE THREAD

**Issue by luncht1me** [MyHush/hush#2]
Running ./zcutil/build.sh -j$(nproc) fails on Manjaro 64bit

```
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system-mt... no
configure: error: Could not link against boost_system-mt !
```

The zCash solution is to run build.sh w/ `--disable-proton`, but even though this is present in the configuration file, the script doesn't accept it, "invalid argument --disable-proton"
 **edit: I see that disable-proton is default on the build file.**

I'm currently attempting to change `PREFIX="/usr/"` to see if that works
update: somehow didn't pick up on the db headers.

Tried now with setting `--with-boost-libdir=/usr/lib64` still getting same error.

**Comment by luncht1me** [comment]
Further investigation leads me to think that there's a problem w/ autobuild and archlinux which uses currently boost 1.64

Attempting to build 1.55 from source, then pointing --with-boost=/opt/boost_1_55_0 and seeing if it builds.

**Comment by madbuda** [comment]
The boost error is due to it not compiling. Work around is to install gcc and g++ 5
pacman -S gcc5 g++5
then go to /usr/bin and move gcc to gcc-7 and g++ to g++-7
symlink gcc and g++ 5 "ln -s gcc-5 gcc" & "ln -s g++-5 g++"

get a fresh clone and build away
