### ISSUE TITLE
Releases needs prebuilt binaires

### ISSUE THREAD

**Issue by aayanl** [MyHush/hush#20]
### Describe the issue
No one likes building stuff that takes 10 minutes - 1 hour constantly. Including .debs and .zips of prebuilt binaries is always useful

#### If so, please list the steps to reproduce below:
1. go to  https://github.com/MyHush/hush
2. be disappointed you have to build
3. wait 10 minutes

### Expected behaviour
1. go to https://github.com/MyHush/hush
2. click releases
3. download
4. dpkg -i hush.deb

### Any extra information that might be useful in the debugging process.
There's a script to automatically package binaries into a deb in zcutil
https://github.com/MyHush/hush/blob/master/zcutil/build-debian-package.sh

**Comment by leto** [comment]
:+1: , once we have a release, let's make it as easy as possible for people to get it

**Comment by matthewjamesr** [comment]
Next-gen Hush wallet can solve this. It will be a pre-built binary that could build hush for the user on first-run. I just download the proper binary.

**Comment by madbuda** [comment]
Prebuilt for nodes as well

**Comment by madbuda** [comment]
https://github.com/MyHush/hush/pull/31
