### ISSUE TITLE
Default hush nodes

### ISSUE THREAD

**Issue by leto** [MyHush/hush#25]
### Describe the issue
No list of default nodes

#### If so, please list the steps to reproduce below:
1. No
2. Default
3. Nodes

### Expected behaviour

This:

```
addnode=us.madmining.club
addnode=183.89.226.141
addnode=163.172.70.26
addnode=76.188.211.191
addnode=173.212.196.148
addnode=78.94.32.197
addnode=77.78.12.89
addnode=78.46.88.113
addnode=163.172.70.26
addnode=192.99.3.29
addnode=144.76.62.229
addnode=163.172.64.208
addnode=37.187.167.145
addnode=[2607:5300:60:341d::1]
addnode=[2001:41d0:d:691::]
addnode=[2a02:c207:2008:8708::1]
addnode=[2001:470:1f09:3b6:7285:c2ff:fe0e:1664]
addnode=[2a02:908:162:67dc:225:90ff:fe50:2b9b]
```

### Actual behaviour + errors

Nothing

### The version of Hush you were using:
All

**Comment by madbuda** [comment]
There are 3 nodes set by default in hushd I don't see this being an issue

**Comment by matthewjamesr** [comment]
I think it is important to take this info and create a seeder living at `nodes.myhush.org` for example.

**Comment by madbuda** [comment]
I'm moving some servers around, but will get a dnsseed instance online.

**Comment by matthewjamesr** [comment]
A good variety of nodes on different interfaces is now in `README.md`. Closing this issue.
