### ISSUE TITLE
hush-cli restart

### ISSUE THREAD

**Issue by leto** [MyHush/hush#26]
### Describe the issue

No easy way to restart hushd

```
$ ./src/hush-cli restart
error code: -32601
error message:
Method not found
```

#### If so, please list the steps to reproduce below:
1. Try to restart
2. Get an amazingly not useful error message
3. See above

### Expected behaviour

The `hushd` daemon should restart.

### Actual behaviour + errors

Silly error message that is confusing to new users.

### The version of Hush you were using:
```
$ ./src/hushd --version
Zcash Daemon version v1.0.9-c54a837
```

**Comment by madbuda** [comment]
@leto this isn't possible... hush-cli is a jsonRPC client and hushd is a server

We can;t tell hushd to launch it's self, and we can;t tell it to start if it isn't listening
