### ISSUE TITLE
"hush-cli help" references "zcashaddress"

### ISSUE THREAD

**Issue by gadelavega** [MyHush/hush#28]
When running "hush-cli help" command it references "zcashaddress" which could lead to confusion. For example, one line of the returned text shows:
sendtoaddress "zcashaddress" amount ( "comment" "comment-to" subtractfeefromamount )

To avoid confusions, it should return something like:
sendtoaddress "hushaddress" amount ( "comment" "comment-to" subtractfeefromamount )

I saw this on hushd version v1.0.9-9b5ced9

**Comment by leto** [comment]
@radix42 https://github.com/MyHush/hush/pull/30

**Comment by matthewjamesr** [comment]
This fix was merged in 5d3aad5. Thank you.
