### ISSUE TITLE
v1.0.9-mac branch

### ISSUE THREAD

**Issue by ianblenke** [MyHush/hush#3]
I generated a diff between the `radis42/zcash` `v1.0.8-1-mac-gcc` branch and the zcash `v1.0.8` branch to pick up the mac specific differences for a build.

I've generated a v1.0.9-mac branch from the hush v1.0.9-lin branch in my hush fork here:

https://github.com/ianblenke/hush

The only real difference in my patched branch is that I don't have any of the client name changes from MagicBean to AppleSeed as with zcash4mac. There is a README-mac.md that should help building and using this branch.

As this is a new branch, I can't really generate a proper github PR for this.

**Comment by leto** [comment]
@radix42 is this needed anymore, or is it bitrotten?

**Comment by leto** [comment]
Closing this, as the bits have rotted. Please submit a new PR if you would like, thanks!
