### ISSUE TITLE
Fix https://explorer.myhush.org

### ISSUE THREAD

**Issue by leto** [MyHush/hush#38]
### Describe the issue
Currently we are using a self-signed cert which has scary warnings.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Self
2. Signed
3. Cert

### Expected behaviour
Proper cert

### Actual behaviour + errors
Scary warnings to average people :cry:

### The version of Hush you were using:
All

**Comment by madbuda** [comment]
done
