### ISSUE TITLE
Limit upload bandwidth 

### ISSUE THREAD

**Issue by madbuda** [MyHush/hush#5]
https://bitcoin.org/en/full-node#maximum-upload-targets
- [x] Modify hushd src to enable feature
- [ ] Update docs 
- [ ] profit

**Comment by leto** [comment]
:+1:, I want to support small miners on our network, as much as we can

**Comment by madbuda** [comment]
Have a dev build running now with the changes. I'm going to leave it running for a few days to make sure it really limits the traffic.

**Comment by leto** [comment]
@madbuda cool. So `-maxuploadtarget=200` would roughly limit a node to 200 MB per day or 200 blocks per day?

**Comment by madbuda** [comment]
This will limit historic blocks served up by hushd

**Comment by madbuda** [comment]
https://github.com/MyHush/hush/pull/15

This will work for linux nodes until we can add in the option to limit historic blocks

**Comment by matthewjamesr** [comment]
@madbuda Can we merge/close this?

**Comment by madbuda** [comment]
closing #15 solves the issue

**Comment by matthewjamesr** [comment]
Ok thank you @madbuda, closing this issue.

**Comment by matthewjamesr** [comment]
Ok thank you @madbuda, closing this issue.
