### ISSUE TITLE
Build 1.0.12 deb

### ISSUE THREAD

**Issue by leto** [MyHush/hush#57]
Build a deb for 1.0.12 and put in the correct apt repo

**Comment by madbuda** [comment]
There is already a placeholder for this, closing

**Comment by leto** [comment]
@madbuda thanks for closing a nice Github issue to track a complex step, and now we can go back to a checklist item. :+1:

**Comment by madbuda** [comment]
@leto https://github.com/MyHush/hush/tree/master/contrib/debian

It's all there except for how the team internally manages our apt repo, which will not be publicly documented
