### ISSUE TITLE
Reproducible/Deterministic Builds

### ISSUE THREAD

**Issue by leto** [MyHush/hush#60]
### Describe the issue

No deterministic builds

### Can you reliably reproduce the issue?
Yes

### If so, please list the steps to reproduce below:
1. Compile and observe, 
2. No
3. Reproducibility

### Bounty

500HUSH

### Expected behaviour

Since Bitcoin Core and Zcash have reproducible builds, we should as well. It increases the security of our entire ecosystem. 

### Actual behaviour + errors

We do not have Gitian setup

### The version of Hush you were using:
All

### Any extra information that might be useful in the debugging process.

I like tuhtles

**Comment by csharpee** [comment]
@leto, @madbuda, @radix42 and @developers I have been working on some personal projects for Hush. I am not ready to share quite yet. I am excited, but it is simply not ready and takes tedious patience. In the mean time, I felt this should be shared  to help others understand more or what not.

I recommend using vagrant and gitian =) Also works nicely with zcash. Zcash also uses Ansible @leto, should we consider using this too? I am not quite sure if it is needed or not.

![image](https://user-images.githubusercontent.com/18726788/32038195-a7e4f002-b9dd-11e7-8cf0-48cd31854485.png)


Also -- this image may not be 200% correct, once the entire idea is ready to be reviewed I will let the staff check it out first to make corrections or w/e is best for the team and Hush. 

 Note: The massive in your face copyright is because this was submitted to public already via the instructor for college individual project. I don't want history to repeat itself. I put a lot of hard work into this to help me understand better and also share with others to catch up to speed a bit quicker to develop for hush <3.

**Comment by leto** [comment]
To be more clear, this bounty is about porting repro builds from BTC/ZEC to Hush, there is prior art to follow: https://github.com/zcash/zcash/blob/4ee9d712b573bccd36e29134d96eaad54182ebab/contrib/gitian-descriptors/README.md

**Comment by kentsommer** [comment]
@csharpee 

Are you currently working on this (setting up reproducible builds)? If you are, I won't work on this. However, if you aren't currently working on this task, I'm willing to work on it.

**Comment by csharpee** [comment]
Okay - beautiful, yeah I am not working on this at the moment.

**Comment by kentsommer** [comment]
@leto 

I've got builds up and running! If someone could test with the current configuration (uses my fork of hush) that would be great!

The instructions for how to setup your host can be found in the hush-gitian repo. Follow them exactly and you should be good to go! Once this is tested, I'll go ahead and PR my `hush` fork and someone else will have to pull in the two other repos.

Main repos:

1. https://github.com/kentsommer/hush-gitian
2. https://github.com/kentsommer/hush
3. https://github.com/kentsommer/gitian.sigs

**Comment by radix42** [comment]
Great! I'll give it a whirl soon, I may have to update some stuff on my
Ubuntu box tho (haven't done zcash deterministic builds on it for example
in months and months)

**Comment by csharpee** [comment]
I have tested it on Ubuntu 16.04. It built successfully! I started to do this on Amazon EC2 instance and ran into the VT-X error. So I installed via locally on my ol' System76.

```
vagrant@hush-build:~$ ./gitian-build.sh --verify
v1.0.12-dev
~/hush ~
HEAD is now at 28fb18f... More reference fixes
~
~/gitian-builder ~

Verifying v1.0.12-dev Linux

gpg: Signature made Fri 03 Nov 2017 01:01:22 AM GMT
gpg:                using RSA key #####
gpg: Good signature from "Kent Sommer <#####>"
###6D: OK
~
vagrant@hush-build:~$ 
```

**Comment by leto** [comment]
This looks really exciting, looking forward to testing it out!

**Comment by leto** [comment]
@kentsommer I forked the 2 repos into MyHush org

I am currently testing with `ansible 2.2.1.0` and `vagrant 1.9.1` on OS X and I successfully created the Gitian VM, it's currently building  :+1:

**Comment by kentsommer** [comment]
@radix42, @leto 

I've submitted #65 with a few notes on final things that need to be changed to get this fully up and running.

**Comment by leto** [comment]
I got really close:

```
Generating report
5ad058059f14549aca764b9000f5cd6eba53ed98ab3eeb136c87ddbac7606a81  hush-1.0.12-linux64-debug.tar.gz
b1e4af6d9af4119884214f99cf622d2da802c2ff368c75074282236e34c4d1b2  hush-1.0.12-linux64.tar.gz
e5645066615fd9532797870555638cdddd49dc8fe47bc9b716d7ff66c32d3090  src/hush-1.0.12.tar.gz
8d5dd4418b254a919dc4ddc3a9533fc1992ac9d418802729485d638e3687d861  hush-1.0.12-res.yml
Done.
gpg: skipped "F16219F4C23F91112E9C734A8DFCBF8E5A4D8019": No secret key
gpg: signing failed: No secret key
./bin/gsign:11:in `system!': failed to run gpg2 --detach-sign -u "F16219F4C23F91112E9C734A8DFCBF8E5A4D8019" "../gitian.sigs/v1.0.12-dev/F16219F4C23F91112E9C734A8DFCBF8E5A4D8019/hush-1.0.12-build.assert" (RuntimeError)
	from ./bin/gsign:93:in `<main>'
~

Committing v1.0.12-dev Signatures

~/gitian.sigs ~
[master b862538] Add v1.0.12-dev signatures for F16219F4C23F91112E9C734A8DFCBF8E5A4D8019
 1 file changed, 385 insertions(+)
 create mode 100644 v1.0.12-dev/F16219F4C23F91112E9C734A8DFCBF8E5A4D8019/hush-1.0.12-build.assert
~
```

I think this is related to the fact that I merely specified my keybase pukey ID, but it could not be found locally, perhaps because I am supposed to import it first? @kentsommer

**Comment by kentsommer** [comment]
If you did not specify the key ID [here](https://github.com/MyHush/hush-gitian/blob/master/gitian.yml#L12) then you are correct, you would have to manually import your GPG key to the VM.

**Comment by leto** [comment]
I ran `curl https://keybase.io/dukeleto/key.asc | gpg --import` to import the correct key onto the machine that is the host for the hush-build VM, and now things are chugging along again...

**Comment by leto** [comment]
@kentsommer thanks, I was using the wrong key, `gpg_key_name` instead of `gpg_key_id`, I think that will hopefully fix it and then I will push my assert files. Thanks for the help!

**Comment by radix42** [comment]
do we have a baby steps, one thing at t time doc for setting up gitian
builds? I dunno if the system I was using for it is up right now, and it
needs updating in any case from when i did zcash gitian builds on it

**Comment by kentsommer** [comment]
@radix42

If I understand you correctly, what you are looking for can be found in the readme here: https://github.com/MyHush/hush-gitian

**Comment by radix42** [comment]
awesome thank you, was wondering if that existed :-)

**Comment by radix42** [comment]
I will work on getting that box up tomorrow, I have not enough light to
work on it at night (yes, I know, I am like a hermit in a cave here, lol),
and I'll update all the versions of stuff on it.

**Comment by leto** [comment]
This could be something related to my host GPG being `gpg (GnuPG/MacGPG2) 2.0.14` while the hush-build VM has `gpg (GnuPG) 2.0.26`. I still get `gpg: signing failed: No secret key`. I am using `gpg_key_id: '5A4D8019'` in my gitian.yml

**Comment by radix42** [comment]
ugh you need to actually import your pgp private key i think to be able to
sign stuff, into...which layer of VM, Kent? did you get it to work i can't
recall what I did with zcash gitian it was a PITA with perms

**Comment by kentsommer** [comment]
@leto @radix42 

Yes I've got importing and signing to work. I doubt it is an issue with GPG version mismatch @leto. Did you rerun the `vagrant up --provision hush-build` command after adding the `gpg_key_id` field and verify that Ansible is showing the key was imported correctly?

**Comment by leto** [comment]
when I run `vagrant up --provision hush-build` i finally get:

```
fatal: [hush-build -> localhost]: FAILED! => {"changed": true, "cmd": ["gpg2", "--list-secret-keys", "|", "grep", "5A4D8019"], "delta": "0:00:00.140504", "end": "2017-11-05 19:53:40.453874", "failed": true, "rc": 2, "start": "2017-11-05 19:53:40.313370", "stderr": "gpg: error reading key: No secret key", "stdout": "", "stdout_lines": [], "warnings": []}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

hush-build                 : ok=53   changed=21   unreachable=0    failed=1****
```

with this gitian.yml:
```
---
- name: Apply the Hush Gitian builder role.
  become: yes
  hosts: localhost:hush-build
  vars:
    #hush_git_repo_url: https://github.com/MyHush/hush
    hush_git_repo_url: https://github.com/kentsommer/hush
    hush_version: v1.0.12-dev
    gpg_key_name: '5A4D8019'
    #gpg_key_name: 'F16219F4C23F91112E9C734A8DFCBF8E5A4D8019'
    git_name: 'Duke Leto'
    git_email: 'duke@leto.net'
    # optional - auto imports private key necessary for signing
    gpg_key_id: '5A4D8019'
    # optional
    ssh_key_name: ''
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
```
It seems that only my public key was imported and it does not even try to prompt for a password, because it can't find the secret key

**Comment by kentsommer** [comment]
@leto 

Do you have any output when you run `gpg2 --list-secret-keys` on your host machine?
```
kent@fenix:~$ gpg2 --list-secret-keys
/home/kent/.gnupg/pubring.gpg
-----------------------------
sec   rsa4096/XXXXXXXX 2017-11-01 [SC]
uid         [ultimate] Kent Sommer <kent.sommer13@gmail.com>
ssb   rsa4096/XXXXXXXX 2017-11-01 [E]
```

If so, run again with `gpg2 --list-secret-keys --keyid-format LONG` and copy the ID after the slash on the line starting with `sec` and use that in the `gpg_key_id` field in the [`gitian.yml`](https://github.com/MyHush/hush-gitian/blob/master/gitian.yml) file. 

The entry in `gpg_key_id` should be of length 16.

**Comment by leto** [comment]
@kentsommer thanks for your help, I finally got my Keybase secret key imported to my host gpg correctly, my provision was all green and happy, and now I am running a plain `./gitian-build.sh` again

**Comment by kentsommer** [comment]
@leto 

Awesome! Let me know if there are anymore issues :+1:

**Comment by leto** [comment]
@kentsommer please look this over and let me know if it seems OK: https://github.com/MyHush/gitian.sigs/commit/52a1bbe3f7257d4cefa0214a3d430c7b521290bc

Thanks again, this is super awesome stuff 💯

**Comment by kentsommer** [comment]
@leto 

Those hashes match up with mine. Everything else looks good as well!

**Comment by radix42** [comment]
W00t, so awesome, your assets match

**Comment by peoples** [comment]
Can yinz please remove me from this thread? It all sounds impressive, but I have no idea what it means. Yet it's filling up my inbox.


Please and thank you.


dngbarnes


________________________________

**Comment by lugeb** [comment]
Lol, from @csharpee peoples of the world comment. Someone will remove you.

**Comment by madbuda** [comment]
@peoples github notifications are managed by the users, if you are getting notices then you either subscribed or have been mentioned. You would need to unsubscribe

**Comment by leto** [comment]
@radix42 my vote is that @kentsommer has earned his 500HUSH, his documentation made it very easy to get things setup locally and he was extremely responsive in helping this newb get stuff working

**Comment by radix42** [comment]
I agree, your assets all matched.....i was gonna wait for a third set that
matched, but I am too sick to crawl around under my desk and fix my vagrant
box, so @kentsommer what HUSH addy does the bounty go to? email, PM me or
post a taddr here if you'd like!

when i get my vagrant machine up i wanna setup deterministic build for the
Windows version too, as it is cross compiled on linux and just has some
additional dependencies for the build

**Comment by radix42** [comment]
also @leto I have been trying to discord, slack, signal, call or txt you
the last 30+ minutes and you seem offline aside from the above github reply

**Comment by kentsommer** [comment]
@radix42 

I'm happy to wait for a third set if you would like? My address is here, but feel free to hold off sending until you verify a third set. Would prefer you are confident before sending :+1: 

hush-addr: t1JjmKWun4jn61JgVSK1fQKifVToqhKsov3

**Comment by radix42** [comment]
cool, my vagrant box needs a bit more attention than I thought so its not
up yet (ETOOMUCHCATHAIR in its vents)

**Comment by radix42** [comment]
Bounty happily paid!
https://explorer.myhush.org/tx/0e086a21558875b25db2eb60e39e9754126b4d867426fe9f2063d64458f41678
