### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by leto** [MyHush/hush#63]
### Describe the issue

Hush only supports HTTP and therefore connecting to an RPC backend is only "safe" over localhost, otherwise it would leak lots of metadata and rpc user/pass. Hush should support TLS like Bitcoin and other coins like Zen. Encrypted p2p connections will additionally greatly reduce network metadata available to snoopy people.

### Bounty

TBD

### Can you reliably reproduce the issue?

Yup

#### If so, please list the steps to reproduce below:
1.  Observe
2. No
3. TLS

### Expected behaviour

Support TLS connections,

### Actual behaviour + errors

No TLS

### The version of Hush you were using:
All

### Prior Art

See ZEN's TLS_integration branch: https://github.com/zencashio/zen/compare/master...ZencashOfficial:TLS_integration?expand=1
and the corresponding issue: https://github.com/ZencashOfficial/zen/issues/26

**Comment by radix42** [comment]
if anyone is going to work this bounty, please contact me first to discuss issues with it

**Comment by kentsommer** [comment]
Is anyone currently working on this?

**Comment by csharpee** [comment]
@kentsommer I have spent a lot of time on this, but I am still learning. If I am in the right direction, you can check what I did so far here: https://github.com/csharpee/hush/tree/hush-tls

At the moment, the build is not successful and has header.h files needing to be added or updated --I am still not sure. I read through 124 lines of code and added only tls related things into the hush codebase from ZcashOfficial TLS-Integration help shared by dukeleo.

**Comment by kentsommer** [comment]
@radix42 @csharpee 

I have a secure (TLS enabled node) up and running on hush. Guide for setup and various other documentation is needed but... progress. You were on the right track @csharpee! 

![hush_tls](https://user-images.githubusercontent.com/4055025/32478414-feca87e4-c3c7-11e7-8bb7-4eccbe75da78.png)

**Comment by kentsommer** [comment]
@csharpee 

Hopefully I haven't stepped on any toes, just trying to get hush pushed forward :+1: 

Yes there currently missing:

1. Allowing a user to choose to connect to ONLY TLS nodes. 

Notes for you (@csharpee):

1. SSL ca certs are not required until the actual "runtime" of the node so building is not at all tied with them.

2. Looks like you are just missing a few make params and includes:
    * Some features need to be enabled in: `depends/packages/openssl.mk`
    * Missing `tlskeypath` and `tlscertpath` in: `src/init.cpp`
    * Missing `#include <openssl/bio.h>` and `#include <openssl/ssl.h>` in: `src/net.h`
    * Missing `SSL *ssl;` var definition in: `src/net.h`

**Comment by csharpee** [comment]
No not at all man, I am still learning and am happy to help. You are being more than respectful, I am with you - getting hush pushed forward 👍

**Comment by kentsommer** [comment]
The secure node system in hush will also require something similar to the secure node tracking in zencash (outline is on page 11 and 12 of [their whitepaper](https://zensystem.io/assets/Zen%20White%20Paper.pdf)). 

Not sure what it would look like, but making that system decentralized seems like a good move. 

@radix42 Any thoughts on system architecture?

**Comment by csharpee** [comment]
@kentsommer thanks for the tips man. I got it working. I don't have a CA setup yet though on testting user account. 
@radix42 I am leaving this alone until more direction. 

```
Thank you for running a HUSH node!
You're helping to secure everyone's privacy


In order to ensure you are adequately protecting your privacy when using Hush,
please see <https://github.com/MyHush/hush/blob/master/doc/security.md>.

           Block height | 16865
            Connections | 3
            Secure connections | 3 (TLS: 0)
  Network solution rate | 1 Sol/s
    Local solution rate | 0.4907 Sol/s

You are mining with the tromp solver on 1 threads.

Since starting this node 3 minutes, 40 seconds ago:
- You have validated no transactions.
- You have completed 56 Equihash solver runs.

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]

```

```
$ ./src/hush-cli getmininginfo
{
  "blocks": 16861,
  "currentblocksize": 1000,
  "currentblocktx": 0,
  "difficulty": 7.297981625835189,
  "errors": "",
  "genproclimit": 1,
  "localsolps": 0.3636363636363636,
  "networksolps": 1,
  "networkhashps": 1,
  "pooledtx": 0,
  "testnet": true,
  "chain": "test",
  "generate": true
}
```
```
$ ./src/hush-cli getnetworkinfo
{
  "version": 1001250,
  "subversion": "/BalefulStatic:1.0.12/",
  "protocolversion": 170002,
  "localservices": "0000000000000001",
  "timeoffset": 0,
  "connections": 3,
  **"tls_cert_verified": false,**
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000100,
  "localaddresses": [
  ],
  "warnings": ""
}
```

**Comment by matthewjamesr** [comment]
@kentsommer could you join us in our Discord sometime? @radix42 and I would like to group chat you one night.

**Comment by kentsommer** [comment]
@matthewjamesr 

I'm in the KST (Korean Standard) time zone, but if you had a time in mind (evening or morning my time would be best - busy during the day) I am happy to chat for a bit.

**Comment by aayanl** [comment]
```Not sure what it would look like, but making that system decentralized seems like a good move.``` that's the plan actually once we set up the dao with zen. It can be setup as a layer 2 thing, nodes verify other nodes and check they follow a strict protocol, append it to a list for other nodes to verify and check, the only tricky part is how do we do payments while keeping it anonymous and decentralized

**Comment by kentsommer** [comment]
@aayanl Payments as in rewards to those running the secure nodes?

**Comment by aayanl** [comment]
Yes

**Comment by kentsommer** [comment]
I've confirmed the ability to make TLS connections on the hush testnet:

![hushtls](https://user-images.githubusercontent.com/4055025/32538935-2ed6d4ea-c4ab-11e7-8271-f6ea09a4d71f.png)

I will work on documentation for setup over the next few days in my free time.

**Comment by matthewjamesr** [comment]
Re: managing TLS nodes

I think we can simply manage this by inserting a new config glad `secureonly=0`, or another sensible flag name.

0: False
1: True

We can maintain a second DNS seed for TLS nodes. Thoughts @radix42 @kentsommer @madbuda ?

**Comment by kentsommer** [comment]
@matthewjamesr 

That sounds reasonable to me if we stick with TLS as the peer-to-peer encryption scheme. However, I'm not super set that TLS is the way to go for this security enhancement. I've been looking at the solution proposed in [BIP 151](https://github.com/bitcoin/bips/blob/master/bip-0151.mediawiki) as well.

**Comment by matthewjamesr** [comment]
I'll give it a read. I am ok with whatever the group reaches consenses with.

**Comment by madbuda** [comment]
👍 on [BIP 151](https://github.com/bitcoin/bips/blob/master/bip-0151.mediawiki )

**Comment by matthewjamesr** [comment]
@kentsommer I concur and am ok with BIP 151.

**Comment by matthewjamesr** [comment]
After discussion between myself, @radix42, and @kentsommer, we have decided to PR the TLS branch. BIP 151 will be implemented on a future date/time.

**Comment by aayanl** [comment]
👍 the ca stuff is only unique to zen, glad to see more coins implementing encrypted network stacks 😃

**Comment by kentsommer** [comment]
This is closed out by https://github.com/MyHush/hush/pull/68 :neckbeard:
