### ISSUE TITLE
Make myhush.github.io awesome

### ISSUE THREAD

**Issue by leto** [MyHush/hush#7]
### Describe the issue

It's just a temporary README right now

### Can you reliably reproduce the issue?
Yup

#### If so, please list the steps to reproduce below:
1. It  
2. Looks
3. Bad

### Expected behaviour

Super snazzy developer-oriented website to be an "easy onramp" for Hush devs/miners/pool ops/etc..

### Actual behaviour + errors

Ain't nothin' there

**Comment by matthewjamesr** [comment]
Closing this issue as our blog will be hosted elsewhere.
