### ISSUE TITLE
incorrect size of solution

### ISSUE THREAD

**Issue by savskii** [MyHush/hush#71]
In my Hush pool i have tryed to change diff setting from 0.1 upto 128 and still same errors

could anyone tell me where i messed up ? 

[Pool]      [hush] (Thread 4) Share rejected: {"job":"cccd","ip":"::ffff:31.24.216.135","worker":"t1aPXQqsm9fFZzhFotsYeJyvve3SNgURCQH.Rig18","difficulty":2.4,"error":"incorrect size of solution"}

**Comment by ric77barradas** [comment]
Having same issue anyone can help

**Comment by ric77barradas** [comment]
Hi I am having same issue anyone able to help?

**Comment by minerric** [comment]
having same issue anyone able to shed some light?

**Comment by leto** [comment]
@savskii @minerric If you would like to provide a bounty in HUSH I can help you fix this, it sounds like the data in your Stratum procotol JSON is incorrect or formatted in an incompatible way

**Comment by minerric** [comment]
great sense of community there's a coin i won't support anymore

**Comment by madbuda** [comment]
This is a node-stratum issue and not related to hushd. Closing
