### ISSUE TITLE
Merge latest bitcore

### ISSUE THREAD

**Issue by leto** [MyHush/hush#79]
### Describe the issue

Merge latest bitcore

###  Bounty

500 Hush

## Details

xxx

**Comment by madbuda** [comment]
@leto https://github.com/MyHush/hush/tree/v1.0.13-bitcoreTLS
added in TLS for funsies

**Comment by madbuda** [comment]
Closing, explorers are live with new code

**Comment by leto** [comment]
I agree with the 1000 Bounty for this, its sets the stage for so many things. I will make sure it gets dispersed to @madbuda

**Comment by jl777** [comment]
sent bounty
