### ISSUE TITLE
Hush Messenger Protocol Spec

### ISSUE THREAD

**Issue by leto** [MyHush/hush#8]
### Describe the issue

We need an HMP spec on Github

### Can you reliably reproduce the issue?
Yes

## Bounty

TBD

#### If so, please list the steps to reproduce below:
1. No
2. Spec
3. Exists (outside of @radix42's head)

### Expected behaviour

A publicly viewable spec which we can point people at and take Github Pull Requests on.

**Comment by leto** [comment]
@radix42 can you update this issue with a bounty amount? Or do we want the implementation AND spec to be under one bounty? https://github.com/MyHush/hush/issues/9

**Comment by matthewjamesr** [comment]
Closing, as migrating to HushList.
