### ISSUE TITLE
Barterdex issue

### ISSUE THREAD

**Issue by CryptoXman79** [MyHush/hush#81]
This issue tracker is only for technical issues related to hushd, the Hush node daemon.

General Hush questions and/or support requests and are best directed to the [Hush Forums](https://forum.myhush.org) or [Slack Chat](https://myhush.slack.com).

For reporting security vulnerabilities or for sensitive discussions with our security team, please contact your local nasal demon via ICMP.

### Describe the issue
Please provide a general summary of the issue you're experiencing

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

### The version of Hush you were using:
Run `hushd --version` to find out

### Machine specs:
- OS name + version:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):
- Linux kernel version (uname -a):
- Compiler version (gcc -version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.hush/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a back up of `~/.hush` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.hush` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by CryptoXman79** [comment]
I have the watch only address bug in my swing wallet after sending hushs from barterdex...how can I recovers my funds ?

**Comment by leto** [comment]
We have fixed this watchonly bug in our latest Git code, a new release of the Hush Swing wallet will come soon. We cannot help recover funds that we do not have access to.
