### ISSUE TITLE
Hush Messenger Reference Implementation

### ISSUE THREAD

**Issue by leto** [MyHush/hush#9]
### Describe the issue

The Hush Messenger Protocol needs a reference implementation, hopefully written in a language that does not hate humans.

### Bounty

>= 1000Hush

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. No
2. Implementation
3. Exists

### Expected behaviour

Hush messages shall fly freely, like birds in the wind.

### Actual behaviour + errors

Hush messages dream of the day they will be let from their coops.

### The version of Hush you were using:

All

**Comment by matthewjamesr** [comment]
Closing, as migrating to HushList.

**Comment by fellu** [comment]
Yo. Is this done already? i.e. should I check how HushList work. :)
